package com.billingwebapp.domain;

// Generated Jun 13, 2015 2:39:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblCategoryMaster generated by hbm2java
 */
public class TblCategoryMaster implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private String categoryAliasname;

	public TblCategoryMaster() {
	}

	public TblCategoryMaster(String categoryName, String categoryAliasname) {
		this.categoryName = categoryName;
		this.categoryAliasname = categoryAliasname;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryAliasname() {
		return this.categoryAliasname;
	}

	public void setCategoryAliasname(String categoryAliasname) {
		this.categoryAliasname = categoryAliasname;
	}

}
