package com.billingwebapp.domain;

// Generated Jun 13, 2015 2:39:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblFeatureMaster generated by hbm2java
 */
public class TblFeatureMaster implements java.io.Serializable {

	private Integer featureId;
	private String featureAliasname;
	private String featureName;
	private int featureTypeId;

	public TblFeatureMaster() {
	}

	public TblFeatureMaster(String featureAliasname, String featureName,
			int featureTypeId) {
		this.featureAliasname = featureAliasname;
		this.featureName = featureName;
		this.featureTypeId = featureTypeId;
	}

	public Integer getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(Integer featureId) {
		this.featureId = featureId;
	}

	public String getFeatureAliasname() {
		return this.featureAliasname;
	}

	public void setFeatureAliasname(String featureAliasname) {
		this.featureAliasname = featureAliasname;
	}

	public String getFeatureName() {
		return this.featureName;
	}

	public void setFeatureName(String featureName) {
		this.featureName = featureName;
	}

	public int getFeatureTypeId() {
		return this.featureTypeId;
	}

	public void setFeatureTypeId(int featureTypeId) {
		this.featureTypeId = featureTypeId;
	}

}
