package com.billingwebapp.domain;

// Generated Jun 13, 2015 2:39:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblFeatureTypeMaster generated by hbm2java
 */
public class TblFeatureTypeMaster implements java.io.Serializable {

	private Integer featureTypeId;
	private String featureTypeName;
	private String featureTypeAliasname;

	public TblFeatureTypeMaster() {
	}

	public TblFeatureTypeMaster(String featureTypeName,
			String featureTypeAliasname) {
		this.featureTypeName = featureTypeName;
		this.featureTypeAliasname = featureTypeAliasname;
	}

	public Integer getFeatureTypeId() {
		return this.featureTypeId;
	}

	public void setFeatureTypeId(Integer featureTypeId) {
		this.featureTypeId = featureTypeId;
	}

	public String getFeatureTypeName() {
		return this.featureTypeName;
	}

	public void setFeatureTypeName(String featureTypeName) {
		this.featureTypeName = featureTypeName;
	}

	public String getFeatureTypeAliasname() {
		return this.featureTypeAliasname;
	}

	public void setFeatureTypeAliasname(String featureTypeAliasname) {
		this.featureTypeAliasname = featureTypeAliasname;
	}

}
