package com.billingwebapp.domain;

// Generated Jun 13, 2015 2:39:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblProductInventory generated by hbm2java
 */
public class TblProductInventory implements java.io.Serializable {

	private Integer prodInvId;
	private String prodId;
	private Integer prodInvInventory;

	public TblProductInventory() {
	}

	public TblProductInventory(String prodId, Integer prodInvInventory) {
		this.prodId = prodId;
		this.prodInvInventory = prodInvInventory;
	}

	public Integer getProdInvId() {
		return this.prodInvId;
	}

	public void setProdInvId(Integer prodInvId) {
		this.prodInvId = prodInvId;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public Integer getProdInvInventory() {
		return this.prodInvInventory;
	}

	public void setProdInvInventory(Integer prodInvInventory) {
		this.prodInvInventory = prodInvInventory;
	}

}
