package com.billingwebapp.domain;

// Generated Jun 13, 2015 2:39:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblProductMaster generated by hbm2java
 */
public class TblProductMaster implements java.io.Serializable {

	private String productId;
	private String productName;
	private int brandId;
	private String productAliasname;
	private String productImage;
	private int productInventory;
	private String productImageName;

	public TblProductMaster() {
	}

	public TblProductMaster(String productId, String productName, int brandId,
			String productAliasname, String productImage, int productInventory,
			String productImageName) {
		this.productId = productId;
		this.productName = productName;
		this.brandId = brandId;
		this.productAliasname = productAliasname;
		this.productImage = productImage;
		this.productInventory = productInventory;
		this.productImageName = productImageName;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public int getBrandId() {
		return this.brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	public String getProductAliasname() {
		return this.productAliasname;
	}

	public void setProductAliasname(String productAliasname) {
		this.productAliasname = productAliasname;
	}

	public String getProductImage() {
		return this.productImage;
	}

	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	public int getProductInventory() {
		return this.productInventory;
	}

	public void setProductInventory(int productInventory) {
		this.productInventory = productInventory;
	}

	public String getProductImageName() {
		return this.productImageName;
	}

	public void setProductImageName(String productImageName) {
		this.productImageName = productImageName;
	}

}
