package com.billingwebapp.domain;

// Generated Jun 13, 2015 2:39:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblProductFeatures generated by hbm2java
 */
public class TblProductFeatures implements java.io.Serializable {

	private Integer productFeatureId;
	private String productId;
	private int featureId;

	public TblProductFeatures() {
	}

	public TblProductFeatures(String productId, int featureId) {
		this.productId = productId;
		this.featureId = featureId;
	}

	public Integer getProductFeatureId() {
		return this.productFeatureId;
	}

	public void setProductFeatureId(Integer productFeatureId) {
		this.productFeatureId = productFeatureId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public int getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

}
